### ISSUE TITLE
Feature: ELIF keyword

### ISSUE THREAD

**Issue by MiranDMC** [sannybuilder/dev#248] opened 2023-09-03 03:55 UTC
Please introduce **ELIF** keyword, so switch-like codes:
```
if
	0@ == 1
then
	print_help 'ONE'
else
	if
		0@ == 2
	then
		print_help 'TWO'
	else
		if
			0@ == 2
		then
			print_help 'THREE'
		else
			print_help 'OTHER'
		end
	end
end
```

can be simplified to:
```
if
	0@ == 1
then
	print_help 'ONE'
elif
	0@ == 2
then
	print_help 'TWO'
elif
	0@ == 3
then
	print_help 'THREE'
else
	print_help 'OTHER'
end
```

**Comment by x87** [comment] 2023-09-04 16:29
I think it's a duplicate of https://github.com/sannybuilder/dev/issues/160

**Comment by x87** [comment] 2023-09-10 01:13
I think I prefer `else if` syntax more, so closing this ticket in favor of #160

**Closed by x87** 2023-09-10 01:13 UTC
