### ISSUE TITLE
Disable global variables automatic allocation for Cleo scripts

### ISSUE THREAD

**Issue by MiranDMC** [sannybuilder/dev#326] opened 2024-05-14 12:48 UTC
Global variables seems to be trap that every scripting newcomer falls in.
Recently SB syntax evolved so much that I think automated assigning new named global variable, by just using it, is now out of place.

In my opinion, at least for Cleo scripts, global variables should be only accessible if defined in current mode, declared with **ALLOC** keyword or used numbered approach (like `$409`).

Seems somehow related to: #267

**Comment by x87** [comment] 2024-08-07 03:32
duplicate of #267

**Closed by x87** 2024-08-07 03:32 UTC
