### ISSUE TITLE
Some issues with SB IDE

### ISSUE THREAD

**Issue by firedihm** [sannybuilder/dev#236] opened 2023-07-31 07:54 UTC
I have noticed several non-crucial bugs over time that I want to share.

1. Execution time in post-compile report is evaluated after report window is closed. If you keep report window open for 3s for eg, execution time will display as abnormally large (3000+ms)
![unknown_2023 07 31-10 41](https://github.com/sannybuilder/dev/assets/42544757/71e78abe-36a0-44be-9a19-47b6419fb798)

2. Each {$INCLUDE} seems to affect the position the caret is set when SB throws exception. On screen below with no {$INCLUDE} caret is set at test line when SB throws exception:
![unknown_2023 07 31-10 45_1](https://github.com/sannybuilder/dev/assets/42544757/a01cd9fa-dfc0-4598-9508-e8cd922c8576)

If I add 2 {$INCLUDE}s, then caret will be set 2 lines above test line when SB throws exception:
![unknown_2023 07 31-10 51](https://github.com/sannybuilder/dev/assets/42544757/167ddb5f-c545-4b9b-9443-73358b306a54)

And if I add more...
![unknown_2023 07 31-10 52](https://github.com/sannybuilder/dev/assets/42544757/886d54a0-f196-42cc-941f-aec60a0e316f)

3. Status bar tooltips at the bottom of the window flicker a lot.

**Comment by x87** [comment] 2023-07-31 17:21
> Execution time in post-compile report is evaluated after report window is closed

Just FYI: the report window can be disabled in the Options. https://docs.sannybuilder.com/editor/options/general#show-report
I personally have it disabled as I don't find it much useful for CLEO scripts.

**Comment by x87** [comment] 2023-07-31 17:26
> Status bar tooltips at the bottom of the window flicker a lot.

note: this is a duplicate of #152

**Comment by x87** [comment] 2023-08-05 03:00
> If I add 2 {$INCLUDE}s, then caret will be set 2 lines above test line when SB throws exception:

if you move `{$INCLUDE}s` under `{$CLEO}`, does Sanny show the correct line?

**Comment by firedihm** [comment] 2023-08-05 12:21
> > If I add 2 {$INCLUDE}s, then caret will be set 2 lines above test line when SB throws exception:
> 
> if you move `{$INCLUDE}s` under `{$CLEO}`, does Sanny show the correct line?

yes

**Comment by x87** [comment] 2023-09-05 03:41
ide issues #1 and #3 are fixed in 3.9.0.

#2 is a compiler issue and requires extra research

**Comment by x87** [comment] 2023-10-08 16:20
Extracted second issue into its own ticket, closing this.

**Closed by x87** 2023-10-08 16:20 UTC
Labels: type:nice-to-have, scope:IDE, status:in dev triage
